services:
  reverse_proxy:
    build: ./proxy
    ports:
      - "80:80"
    restart: always

  front:
    build: ./traque-front
    restart: always

  back:
    build: ./traque-back
    restart: always
    environment:
      ADMIN_PASSWORD: 'traquebdsbanger'
      HOST: '0.0.0.0'
      PORT: 3001