services:
  reverse_proxy:
    #image: git.rezel.net/ludotech/traque-proxy:latest
    build: ./proxy
    ports:
      - "80:80"
    restart: always

  front:
    #image: git.rezel.net/ludotech/traque-front:latest
    build: ./traque-front
    restart: always
    environment:
      NEXT_PUBLIC_SOCKET_HOST: 'localhost'
      NEXT_PUBLIC_SOCKET_PORT: 3001
      #NEXT_PUBLIC_SOCKET_HOST: 'traque.rezel.net'

  back:
    #image: git.rezel.net/ludotech/traque-back:latest
    build: ./traque-back
    restart: always
    ports:
      - "3001:3001"
    environment:
      ADMIN_PASSWORD_HASH: '23e3c6886ff8fcba302deac05c46612ed3af99e40a2a14252810f540f3c186aa'
      HOST: '0.0.0.0'
      PORT: 3001


