services:
  proxy:
    restart: always
    ports:
      - "80:80"
    networks:
      - traque-net

  front:
    restart: always
    networks:
      - traque-net

  back:
    restart: always
    environment:
      ADMIN_PASSWORD_HASH: '23e3c6886ff8fcba302deac05c46612ed3af99e40a2a14252810f540f3c186aa'
      HOST: '0.0.0.0'
      PORT: 3001
    networks:
      - traque-net

networks:
  traque-net:
    driver: bridge
