services:
  proxy:
    image: git.rezel.net/ludotech/traque-proxy:latest

  front:
    image: git.rezel.net/ludotech/traque-front:latest
    environment:
      NEXT_PUBLIC_SOCKET_HOST: 'traque.rezel.net'

  back:
    image: git.rezel.net/ludotech/traque-back:latest
