services:
  proxy:
    build: ./proxy

  front:
    build:
      context: ./traque-front
      target: dev
    volumes:
      - ./traque-front:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_SOCKET_HOST: 'localhost'

  back:
    build:
      context: ./traque-back
      target: dev
    volumes:
      - ./traque-back:/app
      - /app/node_modules
